<?php

/**
 * Created by PhpStorm.
 * User: minot_000
 * Date: 6/17/2015
 * Time: 1:23 PM
 */
namespace Kus;
class SyllabusInformation
{
    public $id;
    public $course_id;
    public $office_hour_id;
    public $course_objective;
    public $prerequisite_course;
    public $assignments;
    public $exams;
    public $computer_labs;
    public $software_requirements;
    public $homework_info;
    public $is_active;
}